### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by jasim** [peeyush14goyal/Cafeteria-Management-System#1]
1. Naming conventions. In Ruby we use snake_case. The codebase uses camelcase. For eg: `Order#pendingOrders` should be `Order#pending_orders`. Please make this change for all identifiers across the codebase. While this does not functionally affect the system at all, there is a strong consensus in Ruby and Rails communities on using snake_case.

2. Do not check for `current_user_role == “admin”`. Instead, create ApplicationController methods like `is_admin?` so we can avoid spreading the internal details of how we store user roles across the system. So in future if we have to make a change to how we do role management, then we need to look only in a few localized places.

3. Use the domain terminology in our code. `current_orders` is better called as `cart_orders`, or something similar as long as it clearly indicates that it is for the shopping cart. This approach is called “Ubiquitous language” in Domain driven design. Read more: https://martinfowler.com/bliki/UbiquitousLanguage.html

4. Move logic into model. Controllers should be thin. The purpose of a controller is to simply parse the params and call the appropriate model methods. Think of it as an orchestrator. But why do we do this? This is the core principle behind MVC - Model, View, Controller. The reason we want to centralize all the domain logic in the model is that we might need to use it from different parts of the application. Different controllers might want to use the same behavior. Or we might want to write an external Rake task that will need this same functionality. If we don’t do this grouping of logic together in the model, then over time the codebase will become difficult to work with. If we have to change some behavior, then we wouldn’t know exactly where to look. Logic would be spread out across the codebase and it will become a “tangled mess”. 

	 A few instances where logic should move into model methods:
	 a) UsersController#cart - it removes items that are no longer available.  You could try creating a `CurrentOrder#self.available_items` method to do this.
	 b) OrdersController#update
	 c) Actions in MenusController
	 d) CurrentOrdersController#update

5. Please implement the reports as well (see “Reports” in https://www.pupilfirst.school/targets/2316)

**Comment by peeyush14goyal** [comment]
Worked on feedback and fixed it
