### ISSUE TITLE
User Experience (UX) Review

### ISSUE THREAD

**Issue by jasim** [peeyush14goyal/Cafeteria-Management-System#2]
**How it works**
1. In shopping cart, When I add a quantity to an item, it shows “Quantity is 0” in the flash. I didn’t understand it. Can you make it more descriptive?
2. Can you show the current quantity for each item in the cart in that page? Right now it is not possible to know how many items I have in the cart until I confirm the order.

**How it looks**

1. The opening menu (Go To) is quite clear and nicely done.
2. Do give a highlight to all buttons when hovering. You can do something like: `.divButton:hover { background-color: darkblue; }` This way we get more visual feedback on clickable buttons.
3. In /orders/new, when hovering over an item, it changes the size. That’s a little disorienting for the user. Instead of transforming the size, you could simply change the background color. Or you could give a border. eg: 

```
  		.CurrentOrderItems { border: 1px solid transparent; } 
		  .CurrentOrderItems:hover { border: 1px solid white; } 
```

By giving a 1px transparent border when not hovered, we are able to avoid the div changing its size on hover.

4. In orders/new, each of the item takes a lot of space to see. Can you make it so that it doesn’t take say more than 50px per item? For this you would have to make the picture smaller. You would also want to bring the Quantity entry in the same row as the description, price, and button.
5. In orders/new, the Quantity entry is too small. It is difficult to click on it and increase/decrease. Do make it larger so users have an easier time using it.
6. In orders/new, try to limit the width of the item bar. Right now it is spread over 1300px in a large monitor. So to click on Add I have to move the mouse a lot. Ideally put a `max-width` of around 700 px.
7. In /menus, the menu name is at the extreme left, and its contents are in the center. It is difficult to parse and understand what is going on. Can they be moved so they are closer together? Same for /users/all and other pages that have this layout. 
8. In /menus, the information density in the page is quite low because of a lot of whitespace. I’d recommend reducing the height of each menu item so more content can be packed together. Another option is to make it into a 3 column grid (like how app icons are arranged in Android home screens).

**Comment by peeyush14goyal** [comment]
Worked on feedback and Fixed it
